name: Ingest Event Issue (smoke)

on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ingest workflow YAML is valid"
